// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDml_wdrPJu8w3yxHz_L1c-DU3oRC2McN0',
    appId: '1:784844153527:android:8bb61dc8b45b70b8702332',
    messagingSenderId: '784844153527',
    projectId: 'smarthome101-4b034',
    databaseURL: 'https://smarthome101-4b034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome101-4b034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbZCSBjQgtP6FdFwH7nQBx85dWCS1Tl-g',
    appId: '1:784844153527:ios:6ca1f6eb75c08ee8702332',
    messagingSenderId: '784844153527',
    projectId: 'smarthome101-4b034',
    databaseURL: 'https://smarthome101-4b034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome101-4b034.appspot.com',
    iosBundleId: 'com.example.smartHome101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbZCSBjQgtP6FdFwH7nQBx85dWCS1Tl-g',
    appId: '1:784844153527:ios:6ca1f6eb75c08ee8702332',
    messagingSenderId: '784844153527',
    projectId: 'smarthome101-4b034',
    databaseURL: 'https://smarthome101-4b034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome101-4b034.appspot.com',
    iosBundleId: 'com.example.smartHome101',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEfyLKdtWYsoLNXfXoibArE0-9Tbgo_IE',
    appId: '1:784844153527:web:e466f7a647498c1b702332',
    messagingSenderId: '784844153527',
    projectId: 'smarthome101-4b034',
    authDomain: 'smarthome101-4b034.firebaseapp.com',
    databaseURL: 'https://smarthome101-4b034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome101-4b034.appspot.com',
    measurementId: 'G-HTFRZ3S7Z8',
  );

}